# Generated by Django 3.0.8 on 2020-07-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listings_bidds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='start_bid',
            new_name='price',
        ),
    ]
